### ISSUE TITLE
SignalR Context

### ISSUE THREAD

**Issue by bleekbless** [anuraj/AspNetCoreSamples#1]
How can I use IHubContext<T> in a class, not in a controller ?

**Comment by anuraj** [comment]
You need to use the class as a service, like this.

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddSignalR();
    services.AddScoped(typeof(Sample));
    services.AddMvc();
}
```
And you can inject the IHubContext in the constructor of the class.

```
public class Sample
{
    private readonly IHubContext<Chat> _chatHubContext;
    public Sample(IHubContext<Chat> chatHubContext)
    {
        _chatHubContext = chatHubContext;
    }
}
```

Sorry I closed the issue first, than comment and close.

**Comment by bleekbless** [comment]
@anuraj  I did it, but the context returned is empty, no connections in it and I need to return a response message to the user that made a request...
